### ISSUE TITLE
Page section blueprint : broken and js error thrown

### ISSUE THREAD

**Issue by boguscode** [Daandelange/kirby3-simplestats#38] opened 2023-04-26 20:42 UTC
Hi,

got simplestats up and running to some extend, but when I try to implement the statistics in one of my blueprints, it throws this error, when I enter that particular blueprint in the panel

`Cannot read properties of undefined (reading 'length')`

My Blueprint uses tabs and goes like this:

```
title: MySite


tabs:
  stats:
    label: Stats
    icon: globe
    sections:
      pagestats:
        type: pagestats
        label: TestHeadline
        size: small
        showTotals: true
        showTimeline: true
        showLanguages: true
        showFullInfo: true

  content:
    label: Content
    icon: text
    columns:
      - width: 1/3
        fields:
          titlebar:
            label: Website Title
            type: text
          line1:
            type: line
```

I also enabled the panel view in my config php like this:

```
require_once(__DIR__ . '/../plugins/simplestats/src/models/SimpleStatsTimeFrameUtility.php');
return [
  // [...] your options ...

  // Simplestats
  'daandelange.simplestats.panel.enable' => true, // Disable the panel view completely
  'daandelange.simplestats.tracking.enableReferers' => true, // Disable referer tracking
  'daandelange.simplestats.tracking.timeFrameUtility' => new \daandelange\SimpleStats\SimpleStatsTimeFrameUtilityWeekly(), // Here you can put your custom inherited class from SimpleStatsTimeFrameUtility
  'daandelange.simplestats.tracking.timeFrameUtility' => 'weekly', // Alternative
  'daandelange.simplestats.tracking.method' => \daandelange\SimpleStats\SimpleStatsTrackingMode::OnImage,
];
```

can somebody give me a hint on what's wrong there?

**Comment by Daandelange** [comment] 2023-04-30 08:00
Hi, this is not a configuration mistake but a bug, I think it has been fixed in https://github.com/Daandelange/kirby3-simplestats/commit/4bae997ac62d2aa0258d399b9530973ca95799fb, are you using `master` ?

**Comment by boguscode** [comment] 2023-04-30 21:37
yes, [0.6.2-beta](https://github.com/Daandelange/kirby3-simplestats/releases/tag/0.6.2-beta) from the release page. Are the code changes already in there?

**Comment by Daandelange** [comment] 2023-05-02 06:33
There have quite some changes since `0.6.2`, while no release recently (gotta make one), you could try the master zip meanwhile.

**Comment by boguscode** [comment] 2023-05-02 18:15
I tried master to no avail. the error keeps popping up :(

**Comment by Daandelange** [comment] 2023-05-04 07:13
Sorry, I'm unable to reproduce the error, even with an empty database... could you show me the line from which the error is thrown from ? (the corresponding `somevar.length` and parts around it)

**Comment by boguscode** [comment] 2023-05-04 08:43
I also tried deleting the db and starting anew. No luck.

from where do I get the somevar.length information you'll need? I'm not a programmer unfortunately.
The eroor pops up in my panel.

![Bildschirmfoto 2023-05-04 um 10 42 19](https://user-images.githubusercontent.com/123305208/236154441-cbef69a2-f5bb-45f2-aeb0-599ec20f853d.png)

**Comment by Daandelange** [comment] 2023-05-04 10:12
If you want to try : 
1. Open the developer tools of your browser.
2. In the console area, locate the error that is shown on your screenshot, it will have a link to a file and a line. Click on it.
3. Try to prettify that minimised code so it's easier to read using the `{}` button below the code viewer.
4. Take screenshot of the code area. (you might need to click once again on the file link to highlight the correct line)

**Comment by boguscode** [comment] 2023-05-04 10:29
there's a hole bunch of files involved 

![Bildschirmfoto 2023-05-04 um 12 29 19](https://user-images.githubusercontent.com/123305208/236179394-4c521e88-946d-4e75-b6dd-1dbb27c2f1d2.png)

**Comment by Daandelange** [comment] 2023-05-04 11:58
Sorry, I didn't specify : you need the first one ;)

**Comment by Daandelange** [comment] 2023-05-04 15:21
Ok, I see, I have a local fix for it, but I just came to realise that the page stats section is not working anymore, I need to add timeline features to it and move the old charts to the new common one. It's probably been broken for a while :s
I'll let you know when I have some progress on this.

**Comment by CHE1RON** [comment] 2023-06-06 15:46
Bumping this, as it would be greatly increase its usefulness 😉

**Comment by jonasholfeld** [comment] 2023-10-12 08:34
Hi! Is there a hot fix or a commit for this? Would love to try the plugin but can't get it to work because of the JS error... Thanks a lot!

**Comment by Daandelange** [comment] 2023-10-15 08:08
Hello, sorry, no (hot)fix yet. I hope to address this somewhen soon.
This said, without using the page section, the plugin should work, so you can test it partially. ;)

**Comment by assbach** [comment] 2023-11-15 16:22
looking forward to the fix as well, :) Thank you!

**Comment by Daandelange** [comment] 2023-11-24 17:57
Hi, I just pushed a new version with some improvements on this side. It should work on multi-language websites, I didn't really have the time to test anything in depth. Feel free to try. ;)

**Comment by Daandelange** [comment] 2023-11-25 16:42
As of v0.6.5 it also works correctly in mono language setups, but the layout is still a draft.

Here's how it looks using 2 different blueprint setups :
- ![image](https://github.com/Daandelange/kirby3-simplestats/assets/1329784/c1ba4547-2280-463e-b791-e254d45587a3)
- ![image](https://github.com/Daandelange/kirby3-simplestats/assets/1329784/ff68dfba-e948-4529-9584-fe07ef25b0b6)

It could be of great use to me if you could post a screenshot of how it looks with your custom blueprints, to compare different use cases.

**Closed** 2024-01-12 18:29 UTC
Labels: bug
